read_pdf_task:
  description: >
    Read the contents of the PDF document located at {pdf_path} and identify the main topics.
  expected_output: >
    Text extracted from the PDF document.
  agent: reader_agent


text_processing_task:
  description: >
    Take the provided case study text and structure it into a well-organized format.
    PRESERVE THE ORIGINAL TEXT AS-IS. DO NOT create, modify, or generate new content.
    Your only task is to apply markdown formatting without changing any details.
  agent: text_processor
  expected_output: >
    The output must be IDENTICAL to the provided input, just formatted properly.
    Any hallucination or new content generation is STRICTLY FORBIDDEN.


logo_fetching_task:
  description: >
    Identify the subject matter of the case study and retrieve a relevant logo.
  agent: logo_finder
  expected_output: >
    A URL of the retrieved logo for the specified company or a suitable industry-related logo.

document_formatting_task:
  description: >
    Insert the structured text and logo into a Word document with proper formatting.
    Ensure the document has professional page borders, headers, footers, page numbers,
    and appropriate styling for all elements. Apply the specified color scheme for 
    borders, headers, and content elements to maintain brand consistency.
  agent: document_formatter
  expected_output: >
    A fully formatted Word document containing the case study with all required elements
    and custom color schemes applied.